### ISSUE TITLE
Theme not applying styles (ComponentProvider?)

### ISSUE THREAD

**Issue by horacioh** [jxnblk/gatsby-theme-mdx-blog#14]
for some reason, when using the theme the styles are not being applied to my pages.
here's an example of a gatsby website using the theme and nothing else. The only thing I'm "shadowing" is the `styles.js` to change the `h1` color.

the repo for this example is [here](https://github.com/horacioh/theme-test)

I also even forked the theme repo, add this project to the workspace and use the theme from the workspace thinking maybe the package published to npm was outdated but I;m getting the same result.

Another test I did was inside [codesandbox](https://codesandbox.io/s/jxnblkgatsbythememdxblog-test-mki30) but also it's not working properly :(

If you need more information please let me know!

<img width="1792" alt="index" src="https://user-images.githubusercontent.com/725120/57960550-a7e54d80-7909-11e9-8b55-ec907d75b610.png">
<img width="1792" alt="hello" src="https://user-images.githubusercontent.com/725120/57960549-a7e54d80-7909-11e9-97dc-6dc8ada3b8be.png">

```bash
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.14.0 - ~/.nvm/versions/node/v8.14.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v8.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      react: ^16.8.6 => 16.8.6
```

**Comment by horacioh** [comment]
btw, I'm 100% sure this is something silly I'm doing wrong... hopefully another pair of eyes can point that out.

**Comment by jxnblk** [comment]
Sorry for the delay, taking a look at this now. I can't seem to get the codesandbox running, so I pulled down the repo locally and seeing the same thing. My gut says it's something to do with mis-matched emotion context, since trying to read the theme context just shows an empty object, but I'll keep you posted if I figure anything out

**Comment by horacioh** [comment]
no worries!, I will try to check some things around the emotion context too and see if there's anything I found too.

thanks!

**Comment by jxnblk** [comment]
I'm not entirely sure why you're seeing this issue with the version you have installed, but I've updated dependencies in #15 and published a prerelease at `@jxnblk/gatsby-theme-mdx-blog@0.0.17-0`, which seemed to resolve the issue locally for me. If you have a second to try it out on your end, that'd be super helpful

**Comment by horacioh** [comment]
confirmed. updating the theme solves the problem! 🎉 

thanks!

closing this since the solution is to update `@jxnblk/gatsby-theme-mdx-blog` to version 0.0.17-0
