### ISSUE TITLE
Mobile Navigation

### ISSUE THREAD

**Issue by jletey** [jxnblk/gatsby-theme-mdx-blog#8]
It would be extremely nice if there was mobile navigation. (Like a hamburger button).

For instance, your blog on mobile only shows “Jxnblkblog” and then the button to switch between light and dark mode.

**Comment by jxnblk** [comment]
You can shadow the `header.js` component and put one there. I'm not planning on adding that sort of functionality to this particular theme though

**Comment by jletey** [comment]
Got it ... thanks for the help
